# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import text_pb2 as text__pb2


class TextServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetRelatedWords = channel.stream_stream(
        '/TextService/GetRelatedWords',
        request_serializer=text__pb2.TextRequest.SerializeToString,
        response_deserializer=text__pb2.TextResponse.FromString,
        )


class TextServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetRelatedWords(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TextServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetRelatedWords': grpc.stream_stream_rpc_method_handler(
          servicer.GetRelatedWords,
          request_deserializer=text__pb2.TextRequest.FromString,
          response_serializer=text__pb2.TextResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TextService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
